### ISSUE TITLE
./run_tests fails

### ISSUE THREAD

**Issue by mthaddon** [canonical/prometheus-operator#6]
I've just downloaded the charm code, and from looking in the README.md I tried running the tests, but got:

```
$ ./run_tests 
tests.test_charm (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests.test_charm (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_charm
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/mthaddon/repos/prometheus-operator/prometheus-operator/tests/test_charm.py", line 8, in <module>
    from ops.testing import Harness
ModuleNotFoundError: No module named 'ops'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by facundobatista** [comment]
Did you create the virtualenv and added dependencies as it specifies de "Developing" section previous to "Testing"?

**Comment by balbirthomas** [comment]
@mthaddon Is this still an issue ? Or may I close this issue ?

**Comment by balbirthomas** [comment]
closing issue as it is no longer reproducible. Please reopen if it happens again.
